export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const CHANGE_RATING = 'CHANGE_RATING';
export const REQUEST_PLACES_PENDING = 'REQUEST_PLACES_PENDING';
export const REQUEST_PLACES_SUCCESS = 'REQUEST_PLACES_SUCCESS';
export const REQUEST_PLACES_FAILED = 'REQUEST_PLACES_FAILED';
export const CLEAR_FILTER = 'CLEAR_FILTER';
